#!/usr/bin/env bash
set -euo pipefail

# Local development bootstrap only.
# This wrapper sources runtime values generated by scripts/dev/bootstrap_runtime.sh
# and forwards them to the official MySQL entrypoint. This is NOT production secret management.

/workspace/scripts/dev/bootstrap_runtime.sh

RUNTIME_FILE="/workspace/runtime/dev/runtime.env"
if [[ ! -f "${RUNTIME_FILE}" ]]; then
  echo "Runtime file not found: ${RUNTIME_FILE}" >&2
  exit 1
fi

set -a
source "${RUNTIME_FILE}"
set +a

export MYSQL_ROOT_PASSWORD="${DB_ROOT_PASSWORD}"
export MYSQL_DATABASE="${DB_NAME}"
export MYSQL_USER="${DB_USER}"
export MYSQL_PASSWORD="${DB_PASSWORD}"

exec /usr/local/bin/docker-entrypoint.sh "$@"
